// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  featured_projects: dynamic(() => import("./FeaturedProjects")),
  gallery: dynamic(() => import("./Gallery")),
  image_gallery: dynamic(() => import("./ImageGallery")),
  image_text_section: dynamic(() => import("./ImageTextSection")),
  nav_item: dynamic(() => import("./NavItem")),
  text_block: dynamic(() => import("./TextBlock")),
};
